Repository jordy1611/whats-cookin-JS-JS-KS, pull requests merged in 2020-07, with the labels that each got.

#18 Add pantry psudocode and method placement
  src/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#24 Feature/jms recipe methods1
  data/ingredients.js
  src/Recipe.js
  test/Recipe-test.js
Labels: enhancement

#25 Feature/jcs pantry class iteration1
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#37 Feature/jms html css initiation
  src/Recipe.js
  src/index.html
  src/styles.css
  test/Recipe-test.js
Labels: enhancement

#42 Feature/jcs pantry adjust ing amount
  src/Pantry.js
  src/scripts.js
  test/Pantry-test.js
Labels: enhancement

#43 Feature/jms recipe sad paths
  assets/defualtRecipeImage.jpg
  src/Recipe.js
  test/Recipe-test.js
Labels: enhancement

#48 Feature/jcs script eventlisteners
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/scripts.js
  test/Pantry-test.js
  test/Recipe-test.js
Labels: enhancement

#49 Feature/jms dom refactor cards disply
  data/ingredients.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
Labels: enhancement

#53 Feature/jcs helper functions display pantry
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/scripts.js
  test/Pantry-test.js
  test/Recipe-test.js
  test/User-test.js
Labels: enhancement

#56 Feature/jms hover recipe card functionality
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#68 Feature/jms user recipes display
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#70 Feature/jcs pantry refactor adjust methods
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
Labels: bug

#74 Feature/jms bug fixes
  src/Recipe.js
  src/scripts.js
  test/Recipe-test.js
Labels: enhancement

#75 Fix bug where shopping list was not displaying
  src/index.html
  src/scripts.js
Labels: enhancement

#79 Feature/jcs clean house
  src/Pantry.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
Labels: documentation, enhancement

#81 Feature/jms code clean up
  src/Recipe.js
  src/scripts.js
  test/Recipe-test.js
Labels: documentation, enhancement
